# Generated by Django 5.1.7 on 2025-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("supplier_name", models.CharField(max_length=200)),
                ("warehouse_location", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("product_id", models.CharField(max_length=50, unique=True)),
                ("supplier_id", models.CharField(max_length=50)),
                ("date_received", models.DateField()),
                ("last_order_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("stock_quantity", models.IntegerField()),
                ("reorder_level", models.IntegerField()),
                ("reorder_quantity", models.IntegerField()),
                ("unit_price", models.FloatField()),
                ("sales_volume", models.IntegerField()),
                ("inventory_turnover_rate", models.FloatField()),
                ("percentage", models.FloatField()),
            ],
        ),
    ]
